baseURL = "https://starnumber12046.github.io"
languageCode = "en-us"
title = "StarNumber's blog"
theme = "github-style"
googleAnalytics = ""
pygmentsCodeFences = true
pygmentsUseClasses = true
enableGitalk = true

[params]
  author = "StarNumber12046"
  description = "\"If you want to make a blog from scratch, don't\" - StarNumber12046, 2023"
  github = "StarNumber12046"
  twitter = "NoNumbers046"
  rss = true
  userStatusEmoji = "🚀"
  favicon = "/logo.png"
  location = "localhost:12046"

  [params.gitalk]
    clientID = "406cc20d9057461a4466" 
    clientSecret = "clientsecret"
    repo = "starnumber12046.github.io"
    owner = "StarNumber12046"
    admin = "StarNumber12046"
    id = "location.pathname"
    labels = "gitalk"
    perPage = 30
    pagerDirection = "last"