baseURL = "https://starnumber12046.github.io"
languageCode = "en-us"
title = "StarNumber's blog"
theme = "github-style"
googleAnalytics = ""
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "StarNumber12046"
  description = "\"If you want to make a blog from scratch, don't\" - StarNumber12046, 2023"
  github = "StarNumber12046"
  twitter = "NoNumbers046"
  rss = true
  userStatusEmoji = "🚀"
  favicon = "/logo.png"
  location = "localhost:12046"
