on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  

env:
  NODE_VERSION: '18.x'                # set this to the node version to use

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup pnpm
      uses: pnpm/action-setup@v3.0.0
      with:
        version: 8.15.3
      
    - name: build
      run: |
        pnpm install
        pnpm run build
    - name: Create artifact
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        path: dist # The folder the action should deploy.
        name: actions
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v4.0.5
      with:
        artifact_name: actions
    
